### ISSUE TITLE
WP 4.7 breaks the filter-stopping method used

### ISSUE THREAD

**Issue by stevish-com** [pwkip/contact-form-7-conditional-fields#10]
I'm working on the updated code.

**Comment by stevish-com** [comment]
Here's what I came up with. It's working for me.

https://github.com/pwkip/contact-form-7-conditional-fields/pull/11

**Comment by pwkip** [comment]
Hey stevish.

Thanks for following this project so closely. I tested the code, but it seems that now the shown required fields are not causing any validation errors anymore. Any ideas?

**Comment by stevish-com** [comment]
I'll check it out tomorrow. I've got to follow the project since we kinda
rely on it. It's a small enough plugin that I can see the issues without
making my head spin, so I'm happy to be able to help you while I help my
company.


-Stephen

**Comment by pwkip** [comment]
don't worry about it. i have rewritten some parts of the plugin. most
important is probably that the hidden groups fieldnames are now returned
within the form submission trough ajax. so the double checking which fields
are hidden in php code is now replaced with simply pulling then out of the
submitted form data. i'll try and push the update soon. will update github
now so you can test it out already if you want. any suggestions are welcome
too

**Comment by stevish-com** [comment]
Hey, that sounds great. I'll wait until you've got a stable release since I don't have a dev environment for this particular site anymore. What I've seen of your changes look like a much better way to do it than my manual manipulation of the `$wp_filters` variable
