### ISSUE TITLE
Ability to add class name in group tag

### ISSUE THREAD

**Issue by ghost** [pwkip/contact-form-7-conditional-fields#14]
can you please add  ability of class attribute in group ? that might you remove  for example ` [group group-name class:myClass]`

Thanks

**Comment by pwkip** [comment]
I won't give priority to this issue as there is a pretty basic workaround:

`[group group-1]<div class="mycalss"> ... </div>[/group]`

**Comment by pwkip** [comment]
will be implemented in version 2.2.4
