### ISSUE TITLE
Clear all fields in group on hide (optional)

### ISSUE THREAD

**Issue by pwkip** [pwkip/contact-form-7-conditional-fields#21]
https://wordpress.org/support/topic/condition-under-condition-e-mail/

Extend group like this:
`[group clear-on-hide] ... [/group]`

**Comment by James000r** [comment]
Hi pwkip.

First of all, it is an amazing simple and good working plugin! Thank you a lot.

I tried "clear-on-hide" as well as the in-build suggestion "clear_on_hide", but both solutions do not work.

Could you bring light into this?


```
[group group-567 clear_on_hide][text text-881][/group]
[checkbox typ default:1 "A" "B" "C"
```

Logic works, clearing doesn't. I used chrome, latest version.

Thanks and best regards,
James
