### ISSUE TITLE
add conditional group support to mail attachments field

### ISSUE THREAD

**Issue by pwkip** [pwkip/contact-form-7-conditional-fields#22]
https://wordpress.org/support/topic/conditional-field-for-file-attachments/

**Comment by pwkip** [comment]
fixe in version 1.4.1

**Comment by triggerbox** [comment]
What is the correct way of using this? The following does not attach anything:

```
[group-products-1]uploads/2019/04/product-1.pdf[/group-products-1]
[group-products-2]uploads/2019/04/product-2.pdf[/group-products-2]
[group-products-3]uploads/2019/04/product-3.pdf[/group-products-3]
```

The following attaches everything (regardless of condition):

```
[group-products-1]
uploads/2019/04/product-1.pdf
[/group-products-1]
[group-products-2]
uploads/2019/04/product-2.pdf
[/group-products-2]
[group-products-3]
uploads/2019/04/product-3.pdf
[/group-products-3]
```

**Comment by pwkip** [comment]
Will verify this before next update

**Comment by pwkip** [comment]
verified it again and it still works. If someone could send me a login to a basic wp site where this problem appears, or maybe send me a duplicator installer with their installation. that would be helpful :)

**Comment by SARPPU** [comment]
Today I updated the plugin and still I can not get attaching files to work! Without attachments form works fine but if I have added the possibility to download e.g. pdf file - the form doesn't send.
So if anyone can help me to solve the problem?

**Comment by pwkip** [comment]
For anybody still stumbling on this. I've written some documentation about how to add conditional file attachments: https://conditional-fields-cf7.bdwm.be/conditional-file-attachments/
