### ISSUE TITLE
Test AJAX

### ISSUE THREAD

**Issue by pwkip** [pwkip/contact-form-7-conditional-fields#25]
Test this case:
https://wordpress.org/support/topic/ajax-modal-popup/

**Comment by pwkip** [comment]
Test this one too:
https://wordpress.org/support/topic/display-form-with-conditional-fields-in-a-modal/
Dropbox file: https://www.dropbox.com/s/tqx6qxtb9dd04lp/yz-modal.zip?dl=0

**Comment by pwkip** [comment]
related problem? https://wordpress.org/support/topic/conditional-field-not-working-5/

**Comment by pankajwb** [comment]
@pwkip Facing same issue on bootstrap4 modal. Can you point me in a direction from where to start debugging the issue.

**Comment by lanceadam** [comment]
I'm also experiencing this issue, my conditional fields do not load in modal forms.

**Comment by pwkip** [comment]
Suggestion: https://wordpress.org/support/topic/allow-the-frontend-js-to-be-called-manually/

**Comment by pwkip** [comment]
Possible since version 1.4.4
https://conditional-fields-cf7.bdwm.be/docs/faq/how-to-initialize-the-conditional-logic-after-an-ajax-call/
