### ISSUE TITLE
Clear on hide not working

### ISSUE THREAD

**Issue by pwkip** [pwkip/contact-form-7-conditional-fields#27]
https://wordpress.org/support/topic/clear-on-hide-not-working/

**Comment by pwkip** [comment]
https://wordpress.org/support/topic/clear_on_hide-wont-work-2/

**Comment by pwkip** [comment]
related problem? https://wordpress.org/support/topic/clean-on-hide-checkbox-results-blank-in-email/

**Comment by UVLabs** [comment]
This particular issue is really a deal breaker with using the plugin..

**Comment by pwkip** [comment]
related problem https://wordpress.org/support/topic/children-groups-are-still-showing-after-parent-groups-are-hidden/

**Comment by pwkip** [comment]
related: https://wordpress.org/support/topic/clear_on_hide-is-there-a-workaround/

**Comment by pwkip** [comment]
should be fiex in version 1.4.2
