### ISSUE TITLE
load conditional fields script if a form is loaded, instead of loading it when CF7 scripts are loaded

### ISSUE THREAD

**Issue by pwkip** [pwkip/contact-form-7-conditional-fields#32]
WPCF7 can work without it's natvie scripts. Mailchimp plugin has a setting to disable Ajax. If this setting is enabled CF7CF doesn't work because scripts aren't loaded. TODO: load scripts in a different hook than the wpcf7_load_scripts hook.
https://wordpress.org/support/topic/conditoinal-fields-not-working/#post-11465741

**Comment by brianread108** [comment]
The plugin disabling the JS load was the "PayPal and Stripe addition  to Contact 7".  However is very likely that the MailChimp plugin also can disable it.

**Comment by pwkip** [comment]
should be resolved in latest version.
