### ISSUE TITLE
clear_on_hide not working for multi select

### ISSUE THREAD

**Issue by pwkip** [pwkip/contact-form-7-conditional-fields#35]
Problem: https://conditional-fields-cf7.bdwm.be/clear-on-hide-multi-select/
Reported by mikev10 https://wordpress.org/support/topic/clear-multiselect-when-field-is-hidden/

**Comment by gvaslin** [comment]
I'm stuck with this ! Please find a solution ! 🙏🏻🙏🏻🙏🏻

**Comment by pwkip** [comment]
fixed in version 1.7
