### ISSUE TITLE
Field names

### ISSUE THREAD

**Issue by LoranRendel** [pwkip/contact-form-7-conditional-fields#46]
Plugin doesnt work with fields/groups containing `:` or `.` in name attribute.
WPCF7 works with these fields well.

https://www.w3.org/TR/html401/types.html#type-name

Fix:
`jQuery('[data-id="' + condition.then_field + '"]'`
instead of
`jQuery('[data-id=' + condition.then_field + ']'`

**Comment by pwkip** [comment]
Thanks, will be fixed in the next version.
