### ISSUE TITLE
PRO: Programmatically add repeater fields

### ISSUE THREAD

**Issue by pwkip** [pwkip/contact-form-7-conditional-fields#62]
It should be possible to initialize/update the default number of repeater fields dynamically.

Example use cases:
- Upon loading the form, initialize the form based on the number of fields in a CSV file on the server.
- While on the page, a user uploads a CSV file, after uploading, the number of rows in the csv file are counted, and this number determined the number of repeater fields to show.

Will probably need to add some JavaScript functions, like for example: `wpcf7cf.getRepeater('name-of-repeater').setSubs(12)`

**Comment by pwkip** [comment]
possible since version 1.9.11
https://conditional-fields-cf7.bdwm.be/wp-content/plugins/contact-form-7-conditional-fields-pro/jsdoc-out/wpcf7cf.html#.repeaterSetNumberOfSubs

**Comment by tillschweneker** [comment]
@pwkip Awesome, thanks for the feature!

To fill the content of the newly created repeater subs, I have to use standard JS functions, right? There is no function to fill the fields programmatically, or is it?
