### ISSUE TITLE
Gain Plugin Efficiency, by applying only specific events, only for the relevant to change form fields

### ISSUE THREAD

**Issue by currenge** [pwkip/contact-form-7-conditional-fields#69]
Hi,

I'm providing a complicated form relevant data in a private email, not to expose it publicly, as it may bring to a security vulnerability.

This forms contains like 15 divscreens replaced by jquery activated by clicks on NEXT button, and setting their order on the JS file. On the conditional fields there are about 40 DIV elements of fields to be shown or hidden according to other fields results (including having hidden fields and variables gather in real-time form information, allowing such activation).

I added an old PDF design file allowing to understand initial picture.

Also attached are the CF7 form, the page.php file, and the JS. I did not attache the cumbersome css files.

I know that the new plugin version caused the issue, as removing the plugin gave speed back to the form, and retrieving old plugin's code gave decent speed.

The problem is mainly for change event 'fired' on each text key stroke on textual fields.

**Comment by pwkip** [comment]
closing this in favor of #71
