### ISSUE TITLE
Unclosed p tag if there is a linebreak before [/group]

### ISSUE THREAD

**Issue by erikyo** [pwkip/contact-form-7-conditional-fields#85]
hi @pwkip,

today a user of the wp forum [made me discover](https://wordpress.org/support/topic/send-button-doesnt-work-and-how-send-form-to-sender-mail/#post-14765628) that if you put a empty line before the row with [/group] in the cf7 mail template some non-validable code will be outputted. 

cf7 mail template test:
```
[group g]
<span>yomama</span>

[/group]

[submit "submit"]
```

will return:
```
<div data-id="g" data-orig_data_id="g"  data-class="wpcf7cf_group">
<span>yomama</span></p>
</div>
<p><input type="submit" value="submit" class="wpcf7-form-control wpcf7-submit" /></p>
```

Not critical but this makes my plugin buggy because I use DOMDocument() to parse the form and unclosed tags are not allowed. So please fix  :P 

(wp 5.8 - cf7 5.4.2 - cf7cf 2.0.4)

**Comment by pwkip** [comment]
Hi @erikyo thanks for the bug report. However, I don't believe this is something that should be fixed on my side. groups are converted to divs by the plugin. The p tag is part of the auto-p magic CF7 performs.

If you write this code:
```
<div>
<span>yomama</span>

</div>
```

It will lead to the same problem.
Resulting HTML code:
```
<div>
    <span>yomama</span></p>
</div>
```

So the problem appears either with or without conditional fields.

**Comment by erikyo** [comment]
No, unfortunately I think the problem lies in this code because removing that part the issue disappear:

https://github.com/pwkip/contact-form-7-conditional-fields/blob/ac37f853479c2d6e0009400aaf64e82e27d5897d/cf7cf.php#L421-L454

Anyway, even it was somewhat related to wordpress it need to be [escaped](https://developer.wordpress.org/plugins/security/securing-output/#custom-escaping)... I tried without your plugin enabled and the issue doesn't happen and the generated html is fine. Please, I don't want to keep anymore a fallback (which turned out to be [somewhat fruitless](https://github.com/erikyo/cf7-antispam/issues/12)) to fix an issue that come before my plugin... so please fix it, if you need a hand just ask! 😉

**Comment by pwkip** [comment]
ok, will check again

**Comment by erikyo** [comment]
Thanks! i can explain why this happens in addition.

without the wpcf7cf_properties:
```html
<p>[group g]<br />
 <span>yomama</span></p>
<p>[/group]</p>
```

with:
```html
<div data-id="g" data-orig_data_id="g" data-class="wpcf7cf_group">
<span>yomama</span></p>
</div>
```

It seems that the regex does not work as intended when the line is breaked with a `<br/>`

**Comment by pwkip** [comment]
Hi @erikyo, I tried again with a fresh installation of WP with only CF7 5.6.4 installed, and the problem remains.

If I create a form with this code:

```
<div>
<span>yomama</span>

</div>
```

it results in this HTML:

```
<div>
  <span>yomama</span></p>
</div>
```

The last version of CF7 (5.7) seems to output valid HTML, but it f***s things up with unnecessary `p` tags.
```
<div> 
  <p><br />
    <span>yomama</span>
  </p>
</div>
```

I'm thinking about disabling the `cf7_autop` functionality of CF7 altogether when Conditional fields is active. I could do this by hooking into the `wpcf7_autop_or_not` filter later enough, and always return false. Hope this will not cause too many conflicts...

**Comment by erikyo** [comment]
You're right, the issue is partially due to autop, but I guess that disabling it isn't the right way to fix it... the problem is that [group] is not a true html tag, and this allows the tags to be crossed before the [regex](https://github.com/pwkip/contact-form-7-conditional-fields/blob/ac37f853479c2d6e0009400aaf64e82e27d5897d/cf7cf.php#L421) split... maybe it should be converted to a div before autop?

**Comment by pwkip** [comment]
Well.. it is converted to `<div>` before autop. See my above example. CF7 messes up the HTML later. I could probably go and trim whitespaces and whatnot, but with the pace that CF7 is introducing core changes, I feel like it's okay to disable autop when you install conditional fields. I could introduce it as a new "feature" of conditional fields :)

**Comment by erikyo** [comment]
Ah ok! I just tried again (with the last cf7 version - 5.7) and let's just say it solved it for me, because what matters was that the generated code was valid. Isn't very nice btw, but at least it is valid.

I can confirm that your first example renders like below, so for me the issue is solved (and wasn't in your repo). Thanks for the support!

```
<p><br>
  <span>yomama</span>
</p>
```
